select *from testtable;
select *from details;
select name from details union select name from testtable;
insert testtable (name) values("hanu"),("bharath");
select distinct(gender) from details;
select gender,count(gender) from details group by gender;
update details set gender="male" where name="hanu";
select details.name from details inner join testtable on details.age = testtable.age;
select min(age) from details;
select max(age) from details;
select sum(age) from details;
select details.age,testtable.name from details left join testtable on details.age = testtable.age;
insert into testtable (name,age) values("azar",10),("vijay","22");
use testtable;
create table testtable(name varchar(10),age int(3));
select *from details where name like "s%a";
select *from details order by age desc;
show columns from details;
create database Data;
